import { HelpCircle } from "lucide-react"
import { Trans } from "@lingui/react/macro"

export function TocHintBanner() {
  return (
    <div className="mx-4 mt-3 flex items-start gap-3 rounded-lg border border-amber-200/70 bg-amber-50/60 px-4 py-3">
      <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-100 text-amber-700">
        <HelpCircle className="h-3.5 w-3.5" />
      </span>
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="text-[13px] font-semibold text-amber-900">
          <Trans>How the table of contents works</Trans>
        </span>
        <p className="text-[12px] leading-relaxed text-amber-800/80">
          <Trans>
            Entries were generated by AI. Edit a title, change its indent level, or link it to a
            page. Add and remove entries to match the book's structure. Changes are saved as a new
            version, so you can always roll back.
          </Trans>
        </p>
      </div>
    </div>
  )
}
