import { HelpCircle } from "lucide-react"
import { Trans } from "@lingui/react/macro"

export function CaptionsHintBanner() {
  return (
    <div className="mx-4 mt-3 flex items-start gap-3 rounded-lg border border-teal-200/70 bg-teal-50/60 px-4 py-3">
      <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-teal-100 text-teal-700">
        <HelpCircle className="h-3.5 w-3.5" />
      </span>
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="text-[13px] font-semibold text-teal-900">
          <Trans>How captions work</Trans>
        </span>
        <p className="text-[12px] leading-relaxed text-teal-800/80">
          <Trans>
            Captions were generated by AI. Click any caption to edit it, or mark an image as
            decorative when no caption is needed. Click any image to zoom. Changes are saved as
            a new version, so you can always roll back.
          </Trans>
        </p>
      </div>
    </div>
  )
}
