import { HelpCircle } from "lucide-react"
import { Trans } from "@lingui/react/macro"

export function QuizzesHintBanner() {
  return (
    <div className="mx-4 mt-3 flex items-start gap-3 rounded-lg border border-orange-200/70 bg-orange-50/60 px-4 py-3">
      <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-orange-100 text-orange-700">
        <HelpCircle className="h-3.5 w-3.5" />
      </span>
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="text-[13px] font-semibold text-orange-900">
          <Trans>How quizzes work</Trans>
        </span>
        <p className="text-[12px] leading-relaxed text-orange-800/80">
          <Trans>
            Quizzes were generated by AI from your book's pages. Click any question, option, or
            explanation to edit it, and delete any quiz you don't need. Click a source page to
            zoom. Changes are saved as a new version, so you can always roll back.
          </Trans>
        </p>
      </div>
    </div>
  )
}
